### ISSUE TITLE
Schematic Submission

### ISSUE THREAD

**Issue by timChase98** [charlesjberg/ECE_388_Pedometer#2]
- [x] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [x] All project files should be version controlled 
- [x] Missing schematic 

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by charlesjberg** [comment]
Attempted fix- Changed submission on the main branch, cleaned up pdf upload

**Comment by timChase98** [comment]
Read the datasheet for the correct reset circuitry on the 328.  Everything else looks fine

**Comment by charlesjberg** [comment]
Sounds good thanks Tim

**Comment by charlesjberg** [comment]
[Pedometer_sch.pdf](https://github.com/charlesjberg/ECE_388_Pedometer/files/5530941/Pedometer_sch.pdf)

Fix to reset button to include debounce cap

**Comment by charlesjberg** [comment]
[Pedometer_sch.pdf](https://github.com/charlesjberg/ECE_388_Pedometer/files/5530989/Pedometer_sch.pdf)

**Comment by timChase98** [comment]
I'll accept this, move on to layout.  You need to do some clean up to get a pass
