### ISSUE TITLE
Board Submission 

### ISSUE THREAD

**Issue by timChase98** [charlesjberg/ECE_388_Pedometer#3]
- [ ] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [ ] All project files should be version controlled
- [ ] Boards will not be graded unless both Eagle files and correctly generated Gerber files are present
- [ ] Board edges should be square and parallel
- [ ] Add rounded corners 
- [ ] All traces should hit the center of pads
- [ ] Two traces should never intersect at an acute angle 
- [ ] Silkscreen labels must include
  - [ ] Your Name
  - [ ] Project Name
  - [ ] Date
  - [ ] Version/Rev
  - [ ] Github Link
- [x] Check stock sheet for correct footprints for 
  - [x] Battery Holder
  - [x] Buttons
- [ ] Missing designators for ICs
- [x] Minimize trace length and loop area
- [x] Placement of fiducials should be 
  - [x] FID1 lower left 
  - [x] FID2 upper left
  - [x] FID3 lower right

These are initial comments meant to guide you though the layout process.  I will not look at your board again until your schematic passes review.  This is to reduce the workload on you by limiting the number of times you need to relayout your board due to schematic errors.  

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by timChase98** [comment]
You cannot have traces intersect at acute angles.  This happens on the trace below C1 and on the pin 12 and 13 of IC2.  You are also using the wrong cam processor.  Use the 388 cam processor.  Also please read the submission guidelines completely.

**Comment by charlesjberg** [comment]
attempted fix to acute angle issues, CAM generation, and submission

**Comment by timChase98** [comment]
run the normalize text ULP to fix the stroke width issues.  6mil min to get manufactured

**Comment by charlesjberg** [comment]
Is it 6 mil min size or thickness? I assume size

**Comment by charlesjberg** [comment]
Sorry it must thickness

**Comment by timChase98** [comment]
Did you update the gerebers? I don't see a change?

**Comment by charlesjberg** [comment]
Yes, let me check. I think some of the files remained the same

**Comment by timChase98** [comment]
I think you entered the parameters wrong.  The font got smaller not bigger.

**Comment by charlesjberg** [comment]
Is that right now?

**Comment by timChase98** [comment]
Attach your eagle board file by 6:45pm today and I'll fix it

**Comment by charlesjberg** [comment]
I'm sorry Tim I didn't get to this in time, I'm placing board file on main branch

**Comment by timChase98** [comment]
I just fixed it in the gerber editor.  You are all good

**Comment by charlesjberg** [comment]
Thanks man, really appreciate all your work with this

**Comment by timChase98** [comment]
Your board was sent to fab
